#!/bin/sh

# fdb: streamlined cli budget management
# Copyright (C) 2014 - 2015  David Ulrich
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3 of the License.
# 
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

cmd=luajit
script=fdb.lua

while getopts ":l" opt; do
	case $opt in
		l) # legacy lua mode
			cmd=lua
			;;
		:)
			echo "Unknown option -$OPTARG"
			exit 1
			;;
	esac
done

command $cmd -v >/dev/null 2>&1 || {
	echo "Command $cmd not present"
	exit 2
}

$cmd $script
